import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="title" content="Generated by create next app" />
            </Head>
            <div>Home</div>
        </>
    );
}
