import Providers from '@/shared/providers/providers';
import {DEFAULT_BODY_CLASSNAME} from '@/shared/providers/theme';
import {Suspense} from 'react';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="ru">
            <body className={DEFAULT_BODY_CLASSNAME}>
                <Providers>
                    <Suspense>{children}</Suspense>
                </Providers>
            </body>
        </html>
    );
}
